### ISSUE TITLE
how to remove runtime-config from bosh director.

### ISSUE THREAD

**Issue by abhilash07** [Azure/oms-agent-for-linux-boshrelease#1]
hi thanks for your open-source, is any-one know how to remove runtime-config from director.

Because when we change the vms properties in  yml file and update oms agent is getting error.

**Comment by lizzha** [comment]
Hi, runtime config cannot be removed yet, see https://github.com/cloudfoundry/bosh/issues/1369
It could only be overwritten, so you could workaround it by putting a harmless or already deployed release in the runtime config. e.g. update the yml file like:
```
---
releases:
- name: cf
  version: xxxx
```

**Comment by abhilash07** [comment]
@lizzha Thanks for your information

**Comment by HDYA** [comment]
Close for inactivity.

FYI, this also works (from [BOSH document](https://bosh.io/docs/runtime-config/#example)):

```
---
releases: []
addons: []
```
